name: type_1
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - pip
  - numpy
  - scikit-learn
  - python=3
  - pandas
  - scipy
  - pydantic
  - typer
  - pytest
  - ete3
  - joblib
  - pip:
    - "git+https://github.com/knights-lab/type_1.git"
