#!/usr/bin/env bash
#/usr/bin/time -v shogun coverage -d /project/flatiron2/data/shogun/rep82 -i /project/flatiron2/ben/projects/type_1/data/zymo/ERR2935805/allpath.b6 -o /project/flatiron2/ben/projects/type_1/data/zymo/ERR2935805/coverage.txt -l species -t mapping >> /project/flatiron2/ben/projects/type_1/data/zymo/ERR2935805/shogun_coverage_log.txt 2>&1
#/usr/bin/time -v shogun coverage -d /project/flatiron2/data/shogun/rep82 -i /project/flatiron2/ben/projects/type_1/data/zymo/ERR2984773/allpath.b6 -o /project/flatiron2/ben/projects/type_1/data/zymo/ERR2984773/coverage.txt -l species -t mapping >> /project/flatiron2/ben/projects/type_1/data/zymo/ERR2984773/shogun_coverage_log.txt 2>&1
#/usr/bin/time -v shogun coverage -d /project/flatiron2/data/shogun/rep82 -i /project/flatiron2/ben/projects/type_1/data/bmock_12/SRR8073716/allpath.b6 -o /project/flatiron2/ben/projects/type_1/data/bmock_12/SRR8073716/coverage.txt -l species -t mapping >> /project/flatiron2/ben/projects/type_1/data/bmock_12/SRR8073716/shogun_coverage_log.txt 2>&1
/usr/bin/time -v shogun coverage -d /project/flatiron2/data/shogun/rep82 -i /project/flatiron2/ben/projects/type_1/data/gis_20/ERR3200809/allpath.b6 -o /project/flatiron2/ben/projects/type_1/data/gis_20/ERR3200809/coverage.txt -l species -t mapping >> /project/flatiron2/ben/projects/type_1/data/gis_20/ERR3200809/shogun_coverage_log.txt 2>&1
/usr/bin/time -v shogun coverage -d /project/flatiron2/data/shogun/rep82 -i /project/flatiron2/ben/projects/type_1/data/gis_20/ERR2835738/allpath.b6 -o /project/flatiron2/ben/projects/type_1/data/gis_20/ERR2835738/coverage.txt -l species -t mapping >> /project/flatiron2/ben/projects/type_1/data/gis_20/ERR2835738/shogun_coverage_log.txt 2>&1
/usr/bin/time -v shogun coverage -d /project/flatiron2/data/shogun/rep82 -i /project/flatiron2/ben/projects/type_1/data/mosaic/CS_4/allpath.b6 -o /project/flatiron2/ben/projects/type_1/data/mosaic/CS_4/coverage.txt -l species -t mapping >> /project/flatiron2/ben/projects/type_1/data/mosaic/CS_4/shogun_coverage_log.txt 2>&1
/usr/bin/time -v shogun coverage -d /project/flatiron2/data/shogun/rep82 -i /project/flatiron2/ben/projects/type_1/data/mosaic/CS_3/allpath.b6 -o /project/flatiron2/ben/projects/type_1/data/mosaic/CS_3/coverage.txt -l species -t mapping >> /project/flatiron2/ben/projects/type_1/data/mosaic/CS_3/shogun_coverage_log.txt 2>&1
/usr/bin/time -v shogun coverage -d /project/flatiron2/data/shogun/rep82 -i /project/flatiron2/ben/projects/type_1/data/mosaic/CS_2/allpath.b6 -o /project/flatiron2/ben/projects/type_1/data/mosaic/CS_2/coverage.txt -l species -t mapping >> /project/flatiron2/ben/projects/type_1/data/mosaic/CS_2/shogun_coverage_log.txt 2>&1
/usr/bin/time -v shogun coverage -d /project/flatiron2/data/shogun/rep82 -i /project/flatiron2/ben/projects/type_1/data/mosaic/CS_1/allpath.b6 -o /project/flatiron2/ben/projects/type_1/data/mosaic/CS_1/coverage.txt -l species -t mapping >> /project/flatiron2/ben/projects/type_1/data/mosaic/CS_1/shogun_coverage_log.txt 2>&1
/usr/bin/time -v shogun coverage -d /project/flatiron2/data/shogun/rep82 -i /project/flatiron2/ben/projects/type_1/data/mbarc_26/SRR3656745/allpath.b6 -o /project/flatiron2/ben/projects/type_1/data/mbarc_26/SRR3656745/coverage.txt -l species -t mapping >> /project/flatiron2/ben/projects/type_1/data/mbarc_26/SRR3656745/shogun_coverage_log.txt 2>&1

